<?php
return ['settings'=>[
 'site_name'=>'MentoClock','hero_eyebrow'=>'A clearer working day','hero_title'=>'Good work.\nClearly recorded.','hero_description'=>'Simple clock-in and clock-out for your people. Clear attendance reports for you. One calm view of every workplace.',
 'primary_cta'=>'Let’s talk about your team','features_title'=>'Less chasing. More clarity.','features_description'=>'Give your team a straightforward daily routine, and give managers the records they need.',
 'workflow_title'=>'From first clock-in to a clear report.','pricing_title'=>'A plan that fits your workplace.','pricing_description'=>'Tell us about your people and locations. We’ll confirm the right package, setup and monthly price before you commit.','pricing_note'=>'Packages are configured to your requirements. Any setup, migration or custom-development costs are agreed separately. No payment is taken on this website.',
 'contact_title'=>'Let’s make time simpler.','contact_description'=>'A single shop or a growing group? Tell us what you need and we’ll help you find the right fit.',
 'whatsapp_number'=>'447745975978','contact_email'=>'info@mentosoftware.co.uk','footer_text'=>'By Mento Software. Built for clearer workdays.','site_url'=>'https://mentoclock.com','portal_url'=>'https://mentoclock.com/login','app_store_url'=>'','play_store_url'=>'','seo_title'=>'MentoClock | Employee attendance, clock-in and reports','seo_description'=>'Simplify employee clock-in and clock-out across your shops and workplaces. Explore MentoClock attendance reports, client management and flexible packages.',
 'privacy_text'=>"This notice covers the MentoClock information website. When you make an enquiry, we store the name, business details, email, optional phone number and message you provide so Mento Software can respond. Continue to WhatsApp prepares a message; you choose whether to send it in WhatsApp. WhatsApp handles messages under its own terms and privacy notice.\n\nThis website uses essential session cookies for form protection and administrator access. It does not include advertising or analytics trackers. Limited hashed network identifiers and timestamps are retained for up to 24 hours to help prevent abusive login and form requests.\n\nEnquiry information is normally deleted after 90 days unless follow-up or an agreed service requires longer retention. To request access, correction or deletion, contact the email shown below. This website is separate from the attendance application; employee attendance data is handled under the arrangements agreed with the subscribing business. Your organisation should provide employees with its own attendance and location privacy information.",
 'terms_text'=>"This website provides information about MentoClock and allows businesses to enquire about a package. It does not take payments or activate subscriptions. Package scope, availability, onboarding, pricing and service terms are confirmed in writing before an order is accepted.\n\nAny sample product screens or interactive previews use fictional demonstration data. Attendance totals do not include break deductions, overtime or other payroll adjustments unless expressly agreed. Keep your own employment and payroll policies in place. App-store and client-portal links appear only when configured by the site administrator."
], 'content'=>[
 ['feature','A simple start to every shift','Employees clock in and out from the app, with a clear view of their current status.',['icon'=>'clock']],
 ['feature','The right shop, automatically','One assigned workplace is selected automatically. Employees with several shops choose where they are working.',['icon'=>'shop']],
 ['feature','Location checked at clock time','Foreground location checks help verify a punch against the assigned workplace geofence.',['icon'=>'pin']],
 ['feature','Reports you can actually use','Review daily, weekly and monthly attendance. Download PDFs or CSVs and share the records you need.',['icon'=>'report']],
 ['feature','Your people, in one place','Use the client portal to add and edit employees, manage branches and update assignments.',['icon'=>'people']],
 ['feature','Clearer records, better follow-up','Managers can correct attendance with a reason, while the audit record keeps track of the change.',['icon'=>'check']],
 ['plan','Single workplace','For a shop, café or small team starting with organised attendance.',['monthly'=>'','annual'=>'','audience'=>'One location','features'=>['Employee clock-in and clock-out','Assigned workplace checks','Daily, weekly and monthly reports','Client employee-management portal'],'featured'=>false]],
 ['plan','Multiple workplaces','For businesses coordinating staff across more than one location.',['monthly'=>'','annual'=>'','audience'=>'Several locations','features'=>['Everything in the single-workplace scope','Multiple branch assignments','Branch-filtered attendance reports','Employee activation and reassignment'],'featured'=>true]],
 ['plan','Tailored setup','For larger teams or organisations with specific onboarding requirements.',['monthly'=>'','annual'=>'','audience'=>'Your requirements','features'=>['Team and location scope agreed together','Onboarding requirements reviewed','Migration or integration needs scoped','A written quote before work starts'],'featured'=>false]],
 ['faq','Can employees work across several shops?','Yes. Administrators can assign multiple branches. An employee with one shop can clock in directly; someone assigned to several shops selects a branch before clocking in.',[]],
 ['faq','Can I download weekly and monthly reports?','Yes. The employee app provides PDF sharing for its own attendance reports. The client portal supports filtered PDF and CSV downloads, plus report email to the administrator’s account address when email delivery is configured.',[]],
 ['faq','Does MentoClock track staff in the background?','The current app captures location when an employee clocks in or out. It does not continuously track background location. GPS checks are helpful but cannot guarantee protection against location spoofing.',[]],
 ['faq','Does this replace payroll software?','MentoClock records elapsed attendance time. Breaks, overtime, holiday and payroll adjustments are not calculated in the current release.',[]],
 ['faq','How do we get started?','Contact us with your team size and locations. We’ll confirm availability, package scope and price, then arrange your business setup and test logins.',[]],
 ['faq','Can I manage my own employees?','Yes. Each business has its own client portal for employee details, branch assignments, activation and reports. Website administrators manage this information site separately.',[]],
 ]];
