@extends('layout')
@section('title', ['overview'=>'Overview','people'=>'Your people','workplaces'=>'Workplaces','attendance'=>'Attendance','company'=>'Company profile'][$section])
@section('content')
@php $people=$employees->where('role','employee'); @endphp
<div class="page-heading"><div><span class="eyebrow">{{$business->name}}</span><h1>{{['overview'=>'A clear view of your workday.','people'=>'Your people','workplaces'=>'Your workplaces','attendance'=>'Attendance records','company'=>'Your company profile'][$section]}}</h1><p>{{['overview'=>'People, time and workplaces. Everything in the right place.','people'=>'Manage your team and the workplaces they can clock into.','workplaces'=>'Set up the locations where your team works.','attendance'=>'Review recorded shifts and make traceable corrections.','company'=>'The details that bring your workspace together.'][$section]}}</p></div><div class="actions">@if($section==='overview')<a class="button secondary" href="{{url('/reports')}}">@include('partials.icon',['name'=>'report'])View reports</a><a class="button" href="{{url('/people')}}#add-employee">@include('partials.icon',['name'=>'plus'])Add employee</a>@elseif($section==='people')<a class="button" href="#add-employee">@include('partials.icon',['name'=>'plus'])Add employee</a>@elseif($section==='workplaces')<a class="button" href="#add-workplace">@include('partials.icon',['name'=>'plus'])Add workplace</a>@elseif($section==='attendance')<a class="button" href="{{url('/reports')}}">@include('partials.icon',['name'=>'report'])Open reports</a>@endif</div></div>
@if($section==='overview')
<div class="stats"><article class="card stat"><div class="stat-head">ACTIVE EMPLOYEES @include('partials.icon',['name'=>'people'])</div><div class="number">{{$people->where('active',true)->count()}}</div><small>{{$people->count()}} employees in your team</small></article><article class="card stat accent"><div class="stat-head">CLOCKED IN NOW @include('partials.icon',['name'=>'clock'])</div><div class="number">{{$workingCount}}</div><small>Open attendance records</small></article><article class="card stat"><div class="stat-head">HOURS TODAY @include('partials.icon',['name'=>'report'])</div><div class="number">{{number_format($todayReport['total_hours'],1)}}</div><small>Recorded time · {{$business->timezone}}</small></article><article class="card stat"><div class="stat-head">YOUR WORKPLACES @include('partials.icon',['name'=>'shop'])</div><div class="number">{{$branches->where('active',true)->count()}}</div><small>Active locations for your team</small></article></div>
<div class="two"><section class="card"><div class="card-head"><div><h2>A week, clearly recorded.</h2><p>{{Carbon\Carbon::parse($weekReport['start'])->format('d M')}} – {{Carbon\Carbon::parse($weekReport['end'])->format('d M Y')}}</p></div><a href="{{url('/reports')}}">View breakdown ↗</a></div><div class="chart-total">{{number_format($weekReport['total_hours'],1)}}<small>hours recorded</small></div><div class="week-chart">@foreach($weekReport['daily'] as $d)<div class="week-day"><strong>{{number_format($d['hours'],1)}}h</strong><progress value="{{$d['hours']}}" max="{{max(1,max(array_column($weekReport['daily'],'hours')))}}" aria-label="{{$d['date']}}: {{$d['hours']}} hours"></progress><span>{{Carbon\Carbon::parse($d['date'])->format('D')}}</span></div>@endforeach</div><p class="caption">Recorded elapsed time, before any payroll or break adjustments.</p></section><section class="card"><div class="card-head"><h2>Your next step.</h2></div><a class="quick-link" href="{{url('/people')}}"><span class="quick-icon">@include('partials.icon',['name'=>'people'])</span><div><strong>Your people</strong><small>Add an employee or update branch access.</small></div>@include('partials.icon',['name'=>'arrow'])</a><a class="quick-link" href="{{url('/workplaces')}}"><span class="quick-icon">@include('partials.icon',['name'=>'shop'])</span><div><strong>Manage workplaces</strong><small>Keep locations and geofences up to date.</small></div>@include('partials.icon',['name'=>'arrow'])</a><a class="quick-link" href="{{url('/reports')}}"><span class="quick-icon">@include('partials.icon',['name'=>'report'])</span><div><strong>Prepare a report</strong><small>Download or email daily, weekly and monthly totals.</small></div>@include('partials.icon',['name'=>'arrow'])</a></section></div>
<section class="card"><div class="card-head"><div><h2>Recent attendance</h2><p>The latest activity across your workplaces.</p></div><a href="{{url('/attendance')}}">All records ↗</a></div>@include('partials.attendance',['rows'=>$records->take(6),'correctable'=>false])</section>
@elseif($section==='people')
<section class="card"><div class="card-head"><h2>Your team <small>· {{$people->count()}} employees</small></h2><span class="caption">Only your business’s employees appear here.</span></div><div class="scroll"><table><thead><tr><th>Employee</th><th>Workplaces</th><th>Status</th><th>Manage</th></tr></thead><tbody>@forelse($people as $e)<tr><td><div class="person-cell"><span class="avatar">{{mb_substr($e->name,0,1)}}</span><div><strong>{{$e->name}}</strong><small>{{$e->email}}</small></div></div></td><td>{{$branches->whereIn('id',$assigned->get($e->id,[]))->pluck('name')->join(', ') ?: 'Not assigned'}}</td><td><span class="badge {{$e->active?'':'inactive'}}">{{$e->active?'Active':'Inactive'}}</span></td><td><div class="actions"><a href="{{url('/employees/'.$e->id.'/edit')}}">Edit details ↗</a><form method="post" action="{{url('/employees/'.$e->id.'/status')}}" data-confirm="{{$e->active?'Deactivate this employee? Their mobile sessions will be revoked.':'Activate this employee?'}}">@csrf<button class="secondary">{{$e->active?'Deactivate':'Activate'}}</button></form></div></td></tr>@empty<tr><td colspan="4"><div class="empty-state">@include('partials.icon',['name'=>'people'])<h3>Your team starts here.</h3><p>Add your first employee and choose their assigned workplaces.</p></div></td></tr>@endforelse</tbody></table></div></section>
<section class="card narrow" id="add-employee"><div class="card-head"><div><h2>Add someone to your team.</h2><p>Create their login and assign the right workplace.</p></div></div>@if($branches->where('active',true)->isEmpty())<div class="note">Create a workplace first so the employee has somewhere to clock in. <a href="{{url('/workplaces')}}">Add a workplace ↗</a></div>@else<form action="{{url('/employees')}}" method="post">@csrf<div class="form-two"><div><label>Name</label><input name="name" value="{{old('name')}}" required maxlength="100" autocomplete="name"></div><div><label>Work email</label><input name="email" value="{{old('email')}}" type="email" required autocomplete="email"></div></div><label>Initial password (6+ characters)</label><input name="password" type="password" minlength="6" maxlength="100" required autocomplete="new-password"><label>Assigned workplaces</label><div class="checks">@foreach($branches->where('active',true) as $b)<label><input type="checkbox" name="branches[]" value="{{$b->id}}" @checked(in_array($b->id,old('branches',[])))>{{$b->name}}</label>@endforeach</div><div class="form-actions"><button>@include('partials.icon',['name'=>'plus'])Create employee</button><small>Share their initial login securely.</small></div></form>@endif</section>
@elseif($section==='workplaces')
<div class="workplace-list">@forelse($branches as $b)<article class="card workplace-card"><div class="card-head"><span class="quick-icon">@include('partials.icon',['name'=>'shop'])</span><span class="badge {{$b->active?'':'inactive'}}">{{$b->active?'Active':'Inactive'}}</span></div><h3>{{$b->name}}</h3><p>{{$b->address}}</p><div class="workplace-meta">@include('partials.icon',['name'=>'pin']){{$b->radius_m}}m clock-in boundary</div><p class="caption">{{$b->latitude}}, {{$b->longitude}}</p><a href="{{url('/branches/'.$b->id.'/edit')}}">Edit workplace ↗</a></article>@empty<div class="card empty-state">@include('partials.icon',['name'=>'shop'])<h3>Your first workplace.</h3><p>Add a location before assigning your employees.</p></div>@endforelse</div>
<section class="card narrow" id="add-workplace"><div class="card-head"><div><h2>Add a workplace.</h2><p>Use the exact coordinates of the location where employees clock in.</p></div></div><form action="{{url('/branches')}}" method="post">@csrf<label>Workplace name</label><input name="name" value="{{old('name')}}" maxlength="100" required><label>Address</label><input name="address" value="{{old('address')}}" maxlength="255" required><div class="form-two"><div><label>Latitude</label><input name="latitude" value="{{old('latitude')}}" type="number" step="any" min="-90" max="90" required></div><div><label>Longitude</label><input name="longitude" value="{{old('longitude')}}" type="number" step="any" min="-180" max="180" required></div></div><label>Geofence radius (metres)</label><input name="radius_m" type="number" value="{{old('radius_m',100)}}" min="50" max="1000" required><div class="form-actions"><button>@include('partials.icon',['name'=>'plus'])Create workplace</button></div></form></section>
@elseif($section==='attendance')
<section class="card"><div class="card-head"><div><h2>Clock in / clock out</h2><p>Latest 200 records · times in {{$business->timezone}}</p></div><span class="badge neutral">Corrections are audit logged</span></div>@include('partials.attendance',['rows'=>$records,'correctable'=>true])<p class="caption">Use Reports for date, employee and workplace filters, PDF/CSV downloads and report email.</p></section>
@elseif($section==='company')
<div class="two equal"><section class="card"><div class="card-head"><h2>Business details</h2><span class="badge">Active workspace</span></div><dl class="profile-details"><div><dt>Business</dt><dd>{{$business->name}}</dd></div><div><dt>Timezone</dt><dd>{{$business->timezone}}</dd></div><div><dt>Contact</dt><dd>{{$profile->contact_name ?? 'Not provided'}}</dd></div><div><dt>Email</dt><dd>{{$profile->contact_email ?? 'Not provided'}}</dd></div><div><dt>Phone</dt><dd>{{$profile->contact_phone ?? 'Not provided'}}</dd></div><div><dt>Package</dt><dd>{{$profile->plan_label ?? 'Agreed with Mento Software'}}</dd></div><div><dt>Address</dt><dd>{{$profile->address ?? 'Not provided'}}</dd></div></dl><div class="note">Need to update these details? Contact Mento Software so we can keep your account up to date.</div></section><section class="card"><div class="card-head"><h2>Your administrators</h2></div>@foreach($employees->where('role','admin') as $e)<div class="activity-item"><strong>{{$e->name}} <span class="badge {{$e->active?'':'inactive'}}">{{$e->active?'Active':'Inactive'}}</span></strong><span>{{$e->email}}</span></div>@endforeach<p class="caption">Administrator access is maintained by Mento Software.</p></section></div>
@endif
@endsection
