@extends('layout')
@section('content')
<span class="eyebrow">CLARITY IN EVERY HOUR</span><h1>Attendance reports</h1><p>Daily, weekly and monthly attendance in {{$report['timezone']}}. Overnight records are split across days.</p>
<div class="card"><form method="get" action="/reports" class="filters"><div><label>Period</label><select name="period">@foreach(['daily','weekly','monthly'] as $p)<option value="{{$p}}" @selected($report['period']===$p)>{{ucfirst($p)}}</option>@endforeach</select></div><div><label>Date within period</label><input type="date" name="date" value="{{$filters['date']??$report['start']}}" required></div><div><label>Employee</label><select name="employee_id"><option value="">All employees</option>@foreach($employees as $e)<option value="{{$e->id}}" @selected(($filters['employee_id']??'')==$e->id)>{{$e->name}}</option>@endforeach</select></div><div><label>Workplace</label><select name="branch_id"><option value="">All workplaces</option>@foreach($branches as $b)<option value="{{$b->id}}" @selected(($filters['branch_id']??'')==$b->id)>{{$b->name}}</option>@endforeach</select></div><button>Apply filters</button></form></div>
<div class="grid"><div class="card"><small>HOURS IN PERIOD</small><div class="number">{{number_format($report['total_hours'],2)}}</div><small>{{$report['start']}} → {{$report['end']}}</small></div><div class="card"><small>ATTENDANCE RECORDS</small><div class="number">{{$report['record_count']}}</div></div><div class="card"><small>ACTIVE RECORDS INCLUDED</small><div class="number">{{$report['active_records']}}</div><small>Hours accrue up to report generation.</small></div></div>
<div class="actions"><a class="button" href="{{url('/reports/download').'?'.http_build_query($filters+['format'=>'pdf'])}}">Download PDF</a><a class="button secondary" href="{{url('/reports/download').'?'.http_build_query($filters+['format'=>'csv'])}}">Download CSV</a><form method="post" action="/reports/email">@csrf @foreach($filters as $k=>$v)<input type="hidden" name="{{$k}}" value="{{$v}}">@endforeach<button class="secondary">Email report to me</button></form></div><p class="caption">Emails go to {{auth()->user()->email}} with PDF and CSV attachments.</p>
<div class="card"><h2>Daily totals</h2><div class="bars">@foreach($report['daily'] as $d)<div class="bar-row"><span>{{$d['date']}}</span><div class="track"><div style="width:{{min(100,$d['hours']/max(1,max(array_column($report['daily'],'hours')))*100)}}%"></div></div><strong>{{number_format($d['hours'],2)}}h</strong></div>@endforeach</div></div>
<div class="card"><h2>Clock in / clock out</h2><div class="scroll"><table><thead><tr><th>Employee</th><th>Workplace</th><th>Clock in</th><th>Clock out</th><th>Hours in period</th><th>Status</th></tr></thead><tbody>@forelse($report['records'] as $r)<tr><td>{{$r['employee']}}<br><small>{{$r['employee_code']}}</small></td><td>{{$r['branch']}}</td><td>{{Carbon\Carbon::parse($r['clock_in'])->format('d M, H:i')}}</td><td>{{$r['clock_out']?Carbon\Carbon::parse($r['clock_out'])->format('d M, H:i'):'—'}}</td><td>{{number_format($r['hours'],2)}}</td><td><span class="badge">{{$r['status']}}</span></td></tr>@empty<tr><td colspan="6">No attendance matches these filters.</td></tr>@endforelse</tbody></table></div></div>
@endsection
