@extends('layout')
@section('title','Client profile')
@section('content')
<div class="page-heading"><div><span class="eyebrow">Client workspace · #{{$business->id}}</span><h1>{{$business->name}}</h1><p>Account details, administrator access and recent changes.</p></div><div class="actions"><span class="badge {{$business->active?'':'inactive'}}">{{$business->active?'Active client':'Suspended'}}</span><a class="button secondary" href="{{url('/platform')}}">All clients</a></div></div>
<div class="stats">@foreach([['people','EMPLOYEES','people'],['workplaces','WORKPLACES','shop'],['working','CLOCKED IN NOW','clock'],['records','ATTENDANCE RECORDS','report']] as [$key,$label,$icon])<article class="card stat"><div class="stat-head">{{$label}} @include('partials.icon',['name'=>$icon])</div><div class="number">{{$stats[$key]}}</div><small>For this client workspace</small></article>@endforeach</div>
<div class="two"><div><section class="card"><div class="card-head"><h2>Client profile</h2></div><form method="post" action="{{url('/platform/clients/'.$business->id)}}">@csrf @include('platform.profile-fields')<div class="form-actions"><button>Save client profile</button></div></form></section><section class="card"><div class="card-head"><div><h2>Business administrators</h2><p>Manage the client’s logins. New passwords revoke existing sessions.</p></div></div>@foreach($admins as $admin)<details class="disclosure"><summary><span class="avatar">{{mb_substr($admin->name,0,1)}}</span>{{$admin->name}} <span class="badge {{$admin->active?'':'inactive'}}">{{$admin->active?'Active':'Inactive'}}</span></summary><form method="post" action="{{url('/platform/clients/'.$business->id.'/admins/'.$admin->id)}}">@csrf<div class="form-two"><div><label>Name</label><input name="name" value="{{$admin->name}}" required maxlength="100"></div><div><label>Email</label><input name="email" type="email" value="{{$admin->email}}" required maxlength="255"></div></div><label>Account status</label><select name="active"><option value="1" @selected($admin->active)>Active</option><option value="0" @selected(!$admin->active)>Inactive</option></select><div class="form-two"><div><label>New password (leave blank to keep)</label><input name="password" type="password" minlength="12" maxlength="72" autocomplete="new-password"></div><div><label>Confirm new password</label><input name="password_confirmation" type="password" minlength="12" maxlength="72" autocomplete="new-password"></div></div><div class="form-actions"><button>Update administrator</button></div></form></details>@endforeach
<details class="disclosure"><summary>@include('partials.icon',['name'=>'plus'])Add a business administrator</summary><form method="post" action="{{url('/platform/clients/'.$business->id.'/admins')}}">@csrf<div class="form-two"><div><label>Name</label><input name="name" required maxlength="100"></div><div><label>Email</label><input name="email" type="email" required maxlength="255"></div></div><div class="form-two"><div><label>Initial password (12–72 bytes)</label><input name="password" type="password" minlength="12" maxlength="72" required autocomplete="new-password"></div><div><label>Confirm password</label><input name="password_confirmation" type="password" minlength="12" maxlength="72" required autocomplete="new-password"></div></div><div class="form-actions"><button>Create administrator</button></div></form></details></section></div>
<div><section class="card"><span class="eyebrow">Workspace access</span><h2>{{$business->active?'An active working relationship.':'Access is currently paused.'}}</h2><p>Suspending a client blocks portal and app access. Records remain available when access is restored.</p><form method="post" action="{{url('/platform/clients/'.$business->id.'/status')}}" data-confirm="{{$business->active?'Suspend this client? Their portal access and mobile sessions will be revoked.':'Activate this client workspace?'}}">@csrf<input type="hidden" name="active" value="{{$business->active?'0':'1'}}"><button class="{{$business->active?'danger':'secondary'}}">{{$business->active?'Suspend client access':'Activate client access'}}</button></form><div class="note">No client data is deleted by changing account status.</div></section><section class="card"><div class="card-head"><h2>Account activity</h2></div>@forelse($activity as $entry)<div class="activity-item"><strong>{{$entry->action}}</strong><span>{{$entry->actor}} · {{Carbon\Carbon::parse($entry->created_at)->format('d M Y, H:i')}} UTC</span></div>@empty<p class="caption">Updates to this profile will appear here.</p>@endforelse</section></div></div>
@endsection
